#!/bin/bash

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
replace_last_line='\r\033[K'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

show_one_time_login()
{
	cd $DOCROOT_PATH
  echo -en "${yellow} Generating one-time-login link... ${NC} "
  one_time_login="$(fin drush --uri=${VIRTUAL_HOST} uli)"
  echo -en "${replace_last_line}${green_bg} One-time-login link:${NC} "
  echo "$one_time_login"
}

show_one_time_login
